name: paytrybe_test
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.4
  ficonsax: ^0.0.3
  pinput: ^2.2.31
  flutter_riverpod: ^2.3.2
  equatable: ^2.0.5
  flutter_multi_formatter: ^2.10.2
  webview_flutter: ^4.0.7
  either_dart: ^0.3.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/svgs/
